stages:
  - test
  - build

.ssh: &ssh
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" 
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - git submodule update --init --recursive


test:
  stage: test
  tags:
  # - arduino
  <<: *ssh 
  script:

  
  #- platformio test --test-port /dev/ttyUSB0
  - echo "need a runner..."
  only: 
  - merge_requests
  - master

build:
  stage: build
  <<: *ssh 
  script:
  - platformio run
  
  #artifacts:
  #  paths:
  #    - .pio/build/pro16MHzatmega328/firmware.elf
  #    - .pio/build/pro16MHzatmega328/firmware.hex
  #  expire_in: 1 week
  #only:
  #- merge_requests
  #- master
