stages:
  - test
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.ssh: &ssh
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh


test:
  stage: test
  tags:
  # - arduino
  <<: *ssh 
  script:
  #- platformio test --test-port /dev/ttyUSB0
  - echo "need a runner..."
  only: 
  - merge_requests
  - master

build:
  stage: build
  <<: *ssh 
  script:
  .ssh: &ssh
  before_script:
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - echo -e "$SSH_DEPLOY_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - platformio run
  #artifacts:
  #  paths:
  #    - .pio/build/pro16MHzatmega328/firmware.elf
  #    - .pio/build/pro16MHzatmega328/firmware.hex
  #  expire_in: 1 week
  #only:
  #- merge_requests
  #- master
